# Generated by Django 4.1 on 2022-08-24 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JunimoDatabaseApp', '0002_rename_resource_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='total_g',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2147483647), django.core.validators.MinValueValidator(0)]),
        ),
    ]
