# Generated by Django 4.1 on 2022-08-23 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JunimoDatabaseApp', '0002_blueprint_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_needed', models.IntegerField()),
                ('blueprint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JunimoDatabaseApp.blueprint')),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JunimoDatabaseApp.resource')),
            ],
        ),
    ]
