# Generated by Django 4.1 on 2022-08-23 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JunimoDatabaseApp', '0003_recipematerial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blueprint',
            old_name='image',
            new_name='recipe_image',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='description',
            new_name='resource_description',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='image',
            new_name='resource_image',
        ),
    ]
