# Generated by Django 4.1 on 2022-08-22 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('junimoDatabase', '0002_recipematerial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeMaterials',
        ),
    ]
