from .models.resource import Resource
from .models.blueprint import Blueprint

resources = [
    Resource("Battery Pack", "It's fully charged with precious energy.", "Battery_Pack.png", "500", "https://stardewvalleywiki.com/Battery_Pack"),
    Resource("Bone Fragment", "A small piece of bone.", "Bone_Fragment.png", "12", "https://stardewvalleywiki.com/Bone_Fragment"),
    Resource("Cinder Shard", "You can feel a warm glow from within this stone.", "Cinder_Shard.png", "50", "https://stardewvalleywiki.com/Cinder_Shard"),
    Resource("Clay", "Used in crafting and construction.", "Clay.png", "20", "https://stardewvalleywiki.com/Clay"),
    Resource("Coal", "A combustible rock that is useful for crafting and smelting.", "Coal.png", "15", "https://stardewvalleywiki.com/Coal"),
    Resource("Copper Bar", "A bar of pure copper.", "Copper_Bar.png", "60", "https://stardewvalleywiki.com/Copper_Bar"),
    Resource("Copper Ore", "A common ore that can be smelted into bars.", "Copper_Ore.png", "5", "https://stardewvalleywiki.com/Copper_Ore"),
    Resource("Fiber", "Raw material sourced from plants.", "Fiber.png", "1", "https://stardewvalleywiki.com/Fiber"),
    Resource("Gold Bar", "A bar of pure gold.", "Gold_Bar.png", "250", "https://stardewvalleywiki.com/Gold_Bar"),
    Resource("Gold Ore", "A precious ore that can be smelted into bars.", "Gold_Ore.png", "25", "https://stardewvalleywiki.com/Gold_Ore"),
    Resource("Hardwood", "A special kind of wood with superior strength and beauty.", "Hardwood.png", "15", "https://stardewvalleywiki.com/Hardwood"),
    Resource("Iridium Bar", "A bar of pure iridium.", "Iridium_Bar.png", "1000", "https://stardewvalleywiki.com/Iridium_Bar"),
    Resource("Iridium Ore", "An exotic ore with many curious properties. Can be smelted into bars.", "Iridium_Ore.png", "100", "https://stardewvalleywiki.com/Iridium_Ore"),
    Resource("Iron Bar", "A bar of pure iron.", "Iron_Bar.png", "120", "https://stardewvalleywiki.com/Iron_Bar"),
    Resource("Iron Ore", "A fairly common ore that can be smelted into bars.", "Iron_Ore.png", "10", "https://stardewvalleywiki.com/Iron_Ore"),
    Resource("Radioactive Bar", "Known by the Zuzu City Safety Commission to cause irreversible bodily harm.", "Radioactive_Bar.png", "3000", "https://stardewvalleywiki.com/Radioactive_Bar"),
    Resource("Radioactive Ore", "It's glowing with dangerous energy... Can be smelted into bars.", "Radioactive_Ore.png", "300", "https://stardewvalleywiki.com/Radioactive_Ore"),
    Resource("Refined Quartz", "A more pure form of quartz.", "Refined_Quartz.png", "50", "https://stardewvalleywiki.com/Refined_Quartz"),
    Resource("Stone", "A common material with many uses in crafting and building.", "Stone.png", "2", "https://stardewvalleywiki.com/Stone"),
    Resource("Quartz", "A clear crystal commonly found in caves and mines.", "Quartz.png", "25", "https://stardewvalleywiki.com/Quartz"),
    Resource("Wood", "A sturdy, yet flexible plant material with a wide variety of uses.", "Wood.png", "2", "https://stardewvalleywiki.com/Wood"),
]

blueprints = [
    Blueprint("Wood Fence","Keeps grass and animals contained!","Wood_Fence.png","Null","https://stardewvalleywiki.com/Wood_Fence"),
    Blueprint("Stone Fence","Lasts longer than a wood fence.","Stone_Fence.png","Null","https://stardewvalleywiki.com/Stone_Fence"),
    Blueprint("Iron Fence","Lasts longer than a stone fence.","Iron_Fence.png","Null","https://stardewvalleywiki.com/Iron_Fence"),
    Blueprint("Hardwood Fence","The most durable type of fence.","Hardwood_Fence.png","Null","https://stardewvalleywiki.com/Hardwood_Fence"),
    Blueprint("Grass Starter","Place this on your farm to start a new patch of grass.","Grass_Starter.png","Null","https://stardewvalleywiki.com/Grass_Starter"),
    Blueprint("Gate","Allows you to pass through a fence.","Gate.png","Null","https://stardewvalleywiki.com/Gate"),
    Blueprint("Chest","A place to store your items.","Chest.png","Null","https://stardewvalleywiki.com/Chest"),
    Blueprint("Torch","Provides a modest amount of light.","Torch.png","Null","https://stardewvalleywiki.com/Torch"),
    Blueprint("Scarecrow","Prevents crows from attacking your crops. Has a limited radius (about 8 'tiles').","Scarecrow.png","Null","https://stardewvalleywiki.com/Scarecrow"),
    Blueprint("Deluxe Scarecrow","Prevents crows from attacking your crops. Has a large radius (about 16 'tiles).","Deluxe_Scarecrow.png","Null","https://stardewvalleywiki.com/Deluxe_Scarecrow"),
    Blueprint("Bee House","Place outside and wait for delicious honey! (Except in Winter).","Bee_House.png","Null","https://stardewvalleywiki.com/Bee_House"),
    Blueprint("Keg","Place a fruit or vegetable in here. Eventually it will turn into a beverage.","Keg.png","Null","https://stardewvalleywiki.com/Keg"),
    Blueprint("Cask","Use in the cellar to age products like wine and cheese.","Cask.png","Null","https://stardewvalleywiki.com/Cask"),
    Blueprint("Furnace","Turns ore and coal into metal bars.","Furnace.png","Null","https://stardewvalleywiki.com/Furnace"),
    Blueprint("Garden Pot","Grows crops from any season when indoors. Outdoors, it can only house seasonal crops.","Garden_Pot.png","Null","https://stardewvalleywiki.com/Garden_Pot"),
    Blueprint("Wood Sign","Use an item on this to change what's displayed. The item won't be consumed.","Wood_Sign.png","Null","https://stardewvalleywiki.com/Wood_Sign"),
    Blueprint("Cheese Press","Turns milk into cheese.","Cheese_Press.png","Null","https://stardewvalleywiki.com/Cheese_Press"),
    Blueprint("Stone Sign","Use an item on this to change what's displayed. The item won't be consumed.","Stone_Sign.png","Null","https://stardewvalleywiki.com/Stone_Sign"),
    Blueprint("Mayonnaise Machine","Turns eggs into mayonnaise.","Mayonnaise_Machine.png","Null","https://stardewvalleywiki.com/Mayonnaise_Machine"),
    Blueprint("Seed Maker","Place crops inside to produce a varying amount of seeds. Doesn't work with fruit tree crops.","Seed_Maker.png","Null","https://stardewvalleywiki.com/Seed_Maker"),
    Blueprint("Loom","Turns raw wool into fine cloth.","Loom.png","Null","https://stardewvalleywiki.com/Loom"),
    Blueprint("Oil Maker","Makes gourmet truffle oil.","Oil_Maker.png","Null","https://stardewvalleywiki.com/Oil_Maker"),
    Blueprint("Recycling Machine","Turns fishing trash into resources.","Recycling_Machine.png","Null","https://stardewvalleywiki.com/Recycling_Machine"),
    Blueprint("Worm Bin","Produces bait on a regular basis. The worms are self-sufficient.","Worm_Bin.png","Null","https://stardewvalleywiki.com/Worm_Bin"),
    Blueprint("Preserves Jar","Turns vegetables into pickles and fruit into jam.","Preserves_Jar.png","Null","https://stardewvalleywiki.com/Preserves_Jar"),
    Blueprint("Charcoal Kiln","Turns 10 pieces of wood into one piece of coal.","Charcoal_Kiln.png","Null","https://stardewvalleywiki.com/Charcoal_Kiln"),
    Blueprint("Tapper","Place on a maple, oak, or pine tree and wait for the reservoir to fill with product!","Tapper.png","Null","https://stardewvalleywiki.com/Tapper"),
    Blueprint("Lightning Rod","Collects energy from lightning storms and turns it into battery packs.","Lightning_Rod.png","Null","https://stardewvalleywiki.com/Lightning_Rod"),
    Blueprint("Slime Incubator","Hatches slimes eggs into slimes. Allows you to raise slimes outdoors.","Slime_Incubator.png","Null","https://stardewvalleywiki.com/Slime_Incubator"),
    Blueprint("Slime Egg-Press","Compresses 100 pieces of slime into a slime egg. It's a miracle of science!","Slime_Egg-Press.png","Null","https://stardewvalleywiki.com/Slime_Egg-Press"),
    Blueprint("Crystalarium","Insert a gem of your choice and it will grow copies.","Crystalarium.png","Null","https://stardewvalleywiki.com/Crystalarium"),
    Blueprint("Mini-Jukebox","Allows you to play your favorite tunes.","Mini-Jukebox.png","Null","https://stardewvalleywiki.com/Mini-Jukebox"),
    Blueprint("Sprinkler","Waters the 4 adjacent tiles every morning.","Sprinkler.png","Null","https://stardewvalleywiki.com/Sprinkler"),
    Blueprint("Quality Sprinkler","Waters the 8 adjacent tiles every morning.","Quality_Sprinkler.png","Null","https://stardewvalleywiki.com/Quality_Sprinkler"),
    Blueprint("Iridium Sprinkler","Waters the 24 adjacent tiles every morning.","Iridium_Sprinkler.png","Null","https://stardewvalleywiki.com/Iridium_Sprinkler"),
    Blueprint("Quality Fertilizer","Improves soil quality, increasing your chance to grow quality crops. Mix into tilled soil.","Quality_Fertilizer.png","Null","https://stardewvalleywiki.com/Quality_Fertilizer"),
    Blueprint("Basic Retaining Soil","This soil has a chance of staying watered overnight. Mix into tilled soil.","Basic_Retaining_Soil.png","Null","https://stardewvalleywiki.com/Basic_Retaining_Soil"),
    Blueprint("Quality Retaining Soil","This soil has a good chance of staying watered overnight. Mix into tilled soil.","Quality_Retaining_Soil.png","Null","https://stardewvalleywiki.com/Quality_Retaining_Soil"),
    Blueprint("Staircase","Use this to move down a level in the mines.","Staircase.png","Null","https://stardewvalleywiki.com/Staircase"),
    Blueprint("Speed-Gro","Stimulates leaf production. Guaranteed to increase growth rate by at least 10%. Mix into tilled soil.","Speed-Gro.png","Null","https://stardewvalleywiki.com/Speed-Gro"),
    Blueprint("Flute Block","Plays a flute sound when you walk past.","Flute_Block.png","Null","https://stardewvalleywiki.com/Flute_Block"),
    Blueprint("Drum Block","Plays a drum sound when you walk past.","Drum_Block.png","Null","https://stardewvalleywiki.com/Drum_Block"),
    Blueprint("Basic Fertilizer","Improves soil quality a little, increasing your chance to grow quality crops. Mix into tilled soil.","Basic_Fertilizer.png","Null","https://stardewvalleywiki.com/Basic_Fertilizer"),
    Blueprint("Tree Fertilizer","Sprinkle on a wild tree to ensure rapid growth, even in winter. Doesn't work on fruit trees.","Tree_Fertilizer.png","Null","https://stardewvalleywiki.com/Tree_Fertilizer"),
    Blueprint("Deluxe Speed-Gro","Stimulates leaf production. Guaranteed to increase growth rate by at least 25%. Mix into tilled soil.","Deluxe_Speed-Gro.png","Null","https://stardewvalleywiki.com/Deluxe_Speed-Gro"),
    Blueprint("Hyper Speed-Gro","Greatly stimulates leaf production. Guaranteed to increase growth rate by at least 33%. Mix into tilled soil.","Hyper_Speed-Gro.png","Null","https://stardewvalleywiki.com/Hyper_Speed-Gro"),
    Blueprint("Deluxe Fertilizer","Greatly improves soil quality, increasing your chance to grow quality crops. Mix into tilled soil.","Deluxe_Fertilizer.png","Null","https://stardewvalleywiki.com/Deluxe_Fertilizer"),
    Blueprint("Deluxe Retaining Soil","This soil has a 100% chance of staying watered overnight. Mix into tilled soil.","Deluxe_Retaining_Soil.png","","https://stardewvalleywiki.com/Deluxe_Retaining_Soil"),
    Blueprint("Cherry Bomb","Generates a small explosion. Stand back!","Cherry_Bomb.png","","https://stardewvalleywiki.com/Cherry_Bomb"),
    Blueprint("Copper Bar","A bar of pure copper.","Copper_Bar.png","","https://stardewvalleywiki.com/Copper_Bar"),
    Blueprint("Iron Bar","A bar of pure iron.","Iron_Bar.png","Furnace","https://stardewvalleywiki.com/Iron_Bar"),
    Blueprint("Gold Bar","A bar of pure gold.","Gold_Bar.png","Furnace","https://stardewvalleywiki.com/Gold_Bar"),
    Blueprint("Ancient Seeds","Could these still grow?","Ancient_Seeds.png","Null","https://stardewvalleywiki.com/Ancient_Seeds"),
    Blueprint("Spring Seeds","An assortment of wild spring seeds.","Spring_Seeds.png","Null","https://stardewvalleywiki.com/Spring_Seeds"),
    Blueprint("Summer Seeds","An assortment of wild summer seeds.","Summer_Seeds.png","Null","https://stardewvalleywiki.com/Summer_Seeds"),
    Blueprint("Fall Seeds","An assortment of wild fall seeds.","Fall_Seeds.png","Null","https://stardewvalleywiki.com/Fall_Seeds"),
    Blueprint("Winter Seeds","An assortment of wild winter seeds.","Winter_Seeds.png","Null","https://stardewvalleywiki.com/Winter_Seeds"),
    Blueprint("Fiber Seeds","Plant these in any season. Does not require watering. Harvest with the scythe. Takes 7 days to grow.","Fiber_Seeds.png","Null","https://stardewvalleywiki.com/Fiber_Seeds"),
    Blueprint("Tea Sapling","Takes 20 days to mature. Produces tea leaves during the final week of each season, except winter. No watering necessary!","Tea_Sapling.png","Null","https://stardewvalleywiki.com/Tea_Sapling"),
    Blueprint("Warp Totem: Farm","Warp directly to your house. Consumed on use.","Warp_Totem:_Farm.png","Null","https://stardewvalleywiki.com/Warp_Totem:_Farm"),
    Blueprint("Warp Totem: Mountains","Warp directly to the mountains. Consumed on use.","Warp_Totem:_Mountains.png","Null","https://stardewvalleywiki.com/Warp_Totem:_Mountains"),
    Blueprint("Warp Totem: Beach","Warp directly to the beach. Consumed on use.","Warp_Totem:_Beach.png","Null","https://stardewvalleywiki.com/Warp_Totem:_Beach"),
    Blueprint("Warp Totem: Desert","Warp directly to Calico Desert. Consumed on use.","Warp_Totem:_Desert.png","Null","https://stardewvalleywiki.com/Warp_Totem:_Desert"),
    Blueprint("Warp Totem: Island","Warp directly to Ginger Island. Consumed on use.","Warp_Totem:_Island.png","Null","https://stardewvalleywiki.com/Warp_Totem:_Island"),
    Blueprint("Rain Totem","Activate to greatly increase the chance for rain tomorrow. Consumed on use.","Rain_Totem.png","Null","https://stardewvalleywiki.com/Rain_Totem"),
    Blueprint("Cookout Kit","Use this to create a cooking campfire, allowing you to cook on-the-go!","Cookout_Kit.png","Null","https://stardewvalleywiki.com/Cookout_Kit"),
    Blueprint("Field Snack","A quick snack to fuel the hungry forager.","Field_Snack.png","Null","https://stardewvalleywiki.com/Field_Snack"),
    Blueprint("Jack-O-Lantern","A whimsical fall decoration.","Jack-O-Lantern.png","Null","https://stardewvalleywiki.com/Jack-O-Lantern"),
    Blueprint("Wood Floor","Place on the ground to create paths or to decorate your floors.","Wood_Floor.png","Null","https://stardewvalleywiki.com/Wood_Floor"),
    Blueprint("Straw Floor","Place on the ground to create paths or to spruce up your floors.","Straw_Floor.png","Null","https://stardewvalleywiki.com/Straw_Floor"),
    Blueprint("Weathered Floor","Place on the ground to create paths or to spruce up your floors.","Weathered_Floor.png","Null","https://stardewvalleywiki.com/Weathered_Floor"),
    Blueprint("Rustic Plank Floor","Place on the ground to create paths or to decorate your floors.","Rustic_Plank_Floor.png","Null","https://stardewvalleywiki.com/Rustic_Plank_Floor"),
    Blueprint("Crystal Floor","Place on the ground to create paths or to spruce up your floors.","Crystal_Floor.png","Null","https://stardewvalleywiki.com/Crystal_Floor"),
    Blueprint("Stone Floor","Place on the ground to create paths or to spruce up your floors.","Stone_Floor.png","Null","https://stardewvalleywiki.com/Stone_Floor"),
    Blueprint("Stone Walkway Floor","Place on the ground to create paths or to decorate your floors.","Stone_Walkway_Floor.png","Null","https://stardewvalleywiki.com/Stone_Walkway_Floor"),
    Blueprint("Brick Floor","Place on the ground to create paths or to decorate your floors.","Brick_Floor.png","Null","https://stardewvalleywiki.com/Brick_Floor"),
    Blueprint("Wood Floor","Place on the ground to create paths or to spruce up your floors.","Wood_Floor.png","Null","https://stardewvalleywiki.com/Wood_Path"),
    Blueprint("Gravel Path","Place on the ground to create paths or to spruce up your floors.","Gravel_Path.png","Null","https://stardewvalleywiki.com/Gravel_Path"),
    Blueprint("Cobblestone Path","Place on the ground to create paths or to spruce up your floors.","Cobblestone_Path.png","Null","https://stardewvalleywiki.com/Cobblestone_Path"),
    Blueprint("Stepping Stone Path","Place on the ground to create paths or to spruce up your floors.","Stepping_Stone_Path.png","Null","https://stardewvalleywiki.com/Stepping_Stone_Path"),
    Blueprint("Crystal Path","Place on the ground to create paths or to spruce up your floors.","Crystal_Path.png","Null","https://stardewvalleywiki.com/Crystal_Path"),
    Blueprint("Wild Bait","A unique recipe from Linus that gives you a chance to catch two fish at once.","Wild_Bait.png","Null","https://stardewvalleywiki.com/Wild_Bait"),
    Blueprint("Bait","Causes fish to bite faster. Must first be attached to a fishing rod.","Bait.png","Null","https://stardewvalleywiki.com/Bait_(item)"),
    Blueprint("Spinner","The shape makes it spin around in the water. Slightly increases the bite-rate when fishing.","Spinner.png","Null","https://stardewvalleywiki.com/Spinner"),
    Blueprint("Magnet","Increases the chance of finding treasures when fishing. However, fish aren't crazy about the taste.","Magnet.png","Null","https://stardewvalleywiki.com/Magnet"),
    Blueprint("Trap Bobber","Increases the chance of finding treasures when fishing. However, fish aren't crazy about the taste.","Trap_Bobber.png","Null","https://stardewvalleywiki.com/Trap_Bobber"),
    Blueprint("Cork Bobber","Slightly increases the size of your 'fishing bar'.","Cork_Bobber.png","Null","https://stardewvalleywiki.com/Cork_Bobber"),
    Blueprint("Dressed Spinner","The metal tab and colorful streamers create an enticing spectacle for fish. Increases the bite-rate when fishing.","Dressed_Spinner.png","Null","https://stardewvalleywiki.com/Dressed_Spinner"),
    Blueprint("Treasure Hunter","Fish don't escape while collecting treasures. Also slightly increases the chance to find treasures.","Treasure_Hunter.png","Null","https://stardewvalleywiki.com/Treasure_Hunter"),
    Blueprint("Barbed Hook","Makes your catch more secure, causing the 'fishing bar' to cling to your catch. Works best on slow, weak fish.","Barbed_Hook.png","Null","https://stardewvalleywiki.com/Barbed_Hook"),
    Blueprint("Oil of Garlic","Drink this and weaker monsters will avoid you.","Oil_of_Garlic.png","Null","https://stardewvalleywiki.com/Oil_of_Garlic"),
    Blueprint("Life Elixir","Restores health to full.","Life_Elixir.png","Null","https://stardewvalleywiki.com/Life_Elixir"),
    Blueprint("Crab Pot","Place it in the water, load it with bait, and check the next day to see if you've caught anything. Works in streams, lakes, and the ocean.","Crab_Pot.png","Null","https://stardewvalleywiki.com/Crab_Pot"),
    Blueprint("Iridium Bar","Glows, attracts items, and increases attack damage by 10%.","Iridium_Bar.png","Null","https://stardewvalleywiki.com/Iridium_Band"),
    Blueprint("Wedding Ring","An old Zuzu City tradition... It's used to ask for another farmer's hand in marriage.","Wedding_Ring.png","Null","https://stardewvalleywiki.com/Wedding_Ring"),
    Blueprint("Ring of Yoba","Occasionally shields the wearer from damage.","Ring_of_Yoba.png","Null","https://stardewvalleywiki.com/Ring_of_Yoba"),
    Blueprint("Sturdy Ring","Cuts the duration of negative status effects in half.","Sturdy_Ring.png","Null","https://stardewvalleywiki.com/Sturdy_Ring"),
    Blueprint("Warrior Ring","Occasionally infuses the wearer with 'warrior energy' after slaying a monster.","Warrior_Ring.png","Null","https://stardewvalleywiki.com/Warrior_Ring"),
    Blueprint("Tub o' Flowers","Flowers planted in an oak barrel. Blooms in spring and summer.","Tub_o'_Flowers.png","Null","https://stardewvalleywiki.com/Tub_o%27_Flowers"),
    Blueprint("Wooden Brazier","Provides a moderate amount of light.","Wooden_Brazier.png","Null","https://stardewvalleywiki.com/Wooden_Brazier"),
    Blueprint("Wicked Statue","There's something unsettling about the looks of this statue.","Wicked_Statue.png","Null","https://stardewvalleywiki.com/Wicked_Statue"),
    Blueprint("Stone Brazier","Provides a moderate amount of light.","Stone_Brazier.png","Null","https://stardewvalleywiki.com/Stone_Brazier"),
    Blueprint("Gold Brazier","Provides a moderate amount of light.","Gold_Brazier.png","Null","https://stardewvalleywiki.com/Gold_Brazier"),
    Blueprint("Campfire","Provides a moderate amount of light.","Campfire.png","Null","https://stardewvalleywiki.com/Campfire"),
    Blueprint("Stump Brazier","Provides a moderate amount of light.","Stump_Brazier.png","Null","https://stardewvalleywiki.com/Stump_Brazier"),
    Blueprint("Carved Brazier","Provides a moderate amount of light.","Carved_Brazier.png","Null","https://stardewvalleywiki.com/Carved_Brazier"),
    Blueprint("Skull Brazier","Provides a moderate amount of light.","Skull_Brazier.png","Null","https://stardewvalleywiki.com/Skull_Brazier"),
    Blueprint("Barrel Brazier","Provides a moderate amount of light.","Barrel_Brazier.png","Null","https://stardewvalleywiki.com/Barrel_Brazier"),
    Blueprint("Marble Brazier","Provides a moderate amount of light.","Marble_Brazier.png","Null","https://stardewvalleywiki.com/Marble_Brazier"),
    Blueprint("Wood Lamp-post","Provides a good amount of light.","Wood_Lamp-post.png","Null","https://stardewvalleywiki.com/Wood_Lamp-post"),
    Blueprint("Iron Lamp-post","Provides a good amount of light.","Iron_Lamp-post.png","Null","https://stardewvalleywiki.com/Iron_Lamp-post"),
    Blueprint("Fairy Dust","Sprinkle on kegs, furnaces, and other refining equipment to instantly receive their product.","Fairy_Dust.png","Null","https://stardewvalleywiki.com/Fairy_Dust"),
    Blueprint("Bug Steak","The last resort of the hungry cave diver.","Bug_Steak.png","Null","https://stardewvalleywiki.com/Bug_Steak"),
    Blueprint("Dark Sign","Use an item on this to change what's displayed. The item won't be consumed.","Dark_Sign.png","Null","https://stardewvalleywiki.com/Dark_Sign"),
    Blueprint("Quality Bobber","Boosts the quality of fish that you catch.","Quality_Bobber.png","Null","https://stardewvalleywiki.com/Quality_Bobber"),
    Blueprint("Stone Chest","A place to store your items.","Stone_Chest.png","Null","https://stardewvalleywiki.com/Stone_Chest"),
    Blueprint("Monster Musk","Spray this on to draw more monsters out of hiding.","Monster_Musk.png","Null","https://stardewvalleywiki.com/Monster_Musk"),
    Blueprint("Mini-Obelisk","Place two on the farm to warp between them.","Mini-Obelisk.png","Null","https://stardewvalleywiki.com/Mini-Obelisk"),
    Blueprint("Bone Mill","Turns bone items into fertilizers.","Bone_Mill.png","Null","https://stardewvalleywiki.com/Bone_Mill"),
    Blueprint("Thorns Ring","When enemies damage you, they will take damage themselves.","Thorns_Ring.png","Null","https://stardewvalleywiki.com/Thorns_Ring"),
    Blueprint("Glowstone Ring","Emits a constant light, and also increases your radius for collecting items.","Glowstone_Ring.png","Null","https://stardewvalleywiki.com/Glowstone_Ring"),
    Blueprint("Farm Computer","Scans the farm and displays useful information.","Farm_Computer.png","Null","https://stardewvalleywiki.com/Farm_Computer"),
    Blueprint("Ostrich Incubator","Hatches ostrich eggs into baby ostriches. Place in a barn.","Ostrich_Incubator.png","Null","https://stardewvalleywiki.com/Ostrich_Incubator"),
    Blueprint("Heavy Tapper","Place on a maple, oak, or pine tree and wait for the reservoir to fill with product! Works twice as fast as a normal tapper.","Heavy_Tapper.png","Null","https://stardewvalleywiki.com/Heavy_Tapper"),
    Blueprint("Geode Crusher","Breaks geodes open automatically. Requires coal to operate.","Geode_Crusher.png","Null","https://stardewvalleywiki.com/Geode_Crusher"),
    Blueprint("Hopper","Items placed inside will automatically be loaded into the machine in front of it.","Hopper.png","Null","https://stardewvalleywiki.com/Hopper"),
    Blueprint("Solar Panel","Slowly generates batteries when left in the sun.","Solar_Panel.png","Null","https://stardewvalleywiki.com/Solar_Panel"),
    Blueprint("Magic Bait","Allows you to catch fish from any season, time, or weather, from whichever type of water you cast into.","Magic_Bait.png","Null","https://stardewvalleywiki.com/Magic_Bait")
]